# -*- coding: utf-8 -*-
"""Drone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAlBhHc_H5H96vj-lvQ5T9MBpvoM9gg1
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

FRAME_FOLDER = "/content/drive/MyDrive/XYZ/VisDrone2019-DET-train/images"

!ls /content/drive/MyDrive/VisDrone2019-DET-train

from google.colab import drive
drive.mount('/content/drive')

model_path = "/content/drive/MyDrive/YOUR_FOLDER/best.pt"

!find /content/drive/MyDrive -name "*.pt"

from google.colab import drive
drive.mount('/content/drive')

model_path = "/content/drive/MyDrive/Colab Notebooks/best.pt"

import os
print("Model exists:", os.path.exists(model_path))

# ==========================================
# FINAL MULTI-VIDEO SURVEILLANCE PIPELINE
# YOLOv8 + Tracking + 60s Loitering + Vehicle Gathering
# SQL Tables + Full Text Display + Output Videos
# ==========================================

!pip install -q ultralytics

import os
import cv2
import math
import sqlite3
import base64
import pandas as pd
from ultralytics import YOLO
from google.colab import files
from IPython.display import display, HTML

# -------------------------
# 1. DISPLAY SETTINGS FOR FULL SQL TEXT
# -------------------------
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# -------------------------
# 2. UPLOAD MULTIPLE VIDEOS
# -------------------------
uploaded = files.upload()

video_files = []
for name in uploaded.keys():
    if name.lower().endswith((".mp4", ".avi", ".mov", ".mkv")):
        video_files.append(f"/content/{name}")

if not video_files:
    raise ValueError("No video files uploaded.")

print("Uploaded videos:")
for v in video_files:
    print(v)

# -------------------------
# 3. MODEL
# -------------------------
MODEL_PATH = "yolov8s.pt"
model = YOLO(MODEL_PATH)
print("Using model:", MODEL_PATH)

# -------------------------
# 4. SETTINGS
# -------------------------
CONF_THRESHOLD = 0.12

DIST_THRESHOLD = 80
MIN_LOITER_SECONDS = 60
LOITER_DISTANCE_THRESHOLD = 60
MAX_MISSING_SECONDS = 7
VEHICLE_PROXIMITY_THRESHOLD = 120

VEHICLE_COUNT_THRESHOLD = 4
MIN_VEHICLE_GATHER_SECONDS = 4

OUTPUT_ROOT = "/content/final_multi_video_outputs"
os.makedirs(OUTPUT_ROOT, exist_ok=True)

# -------------------------
# 5. HELPER FUNCTIONS
# -------------------------
def is_person_label(label_name):
    return str(label_name).lower() == "person"

def is_vehicle_label(label_name):
    return str(label_name).lower() in ["car", "bus", "truck", "motorcycle", "bicycle", "vehicle"]

def min_distance_to_any_vehicle(person_center, vehicle_centers):
    if len(vehicle_centers) == 0:
        return float("inf")
    px, py = person_center
    return min(math.sqrt((px - vx) ** 2 + (py - vy) ** 2) for vx, vy in vehicle_centers)

def frame_to_timestamp(frame_number, fps):
    total_seconds = frame_number / fps
    minutes = int(total_seconds // 60)
    seconds = int(total_seconds % 60)
    return f"{minutes:02d}:{seconds:02d}"

def duration_seconds(start_frame, end_frame, fps):
    return round((end_frame - start_frame) / fps, 2)

def person_label(track_id):
    return f"Person {track_id}"

def play_video_html(path, width=700):
    with open(path, "rb") as f:
        video_bytes = f.read()
    b64 = base64.b64encode(video_bytes).decode()
    return HTML(f"""
    <video width="{width}" controls>
        <source src="data:video/mp4;base64,{b64}" type="video/mp4">
    </video>
    """)

def show_full_table(df):
    if df.empty:
        display(df)
    else:
        display(df.style.set_properties(**{
            "white-space": "normal",
            "text-align": "left"
        }))

# -------------------------
# 6. PROCESS EACH VIDEO
# -------------------------
final_video_paths = []

for video_path in video_files:

    video_name = os.path.basename(video_path).rsplit(".", 1)[0]
    print("\n==============================")
    print("Processing:", video_name)
    print("==============================")

    video_output_dir = os.path.join(OUTPUT_ROOT, video_name)
    os.makedirs(video_output_dir, exist_ok=True)

    raw_output_video = os.path.join(video_output_dir, f"{video_name}_annotated.mp4")
    fixed_output_video = os.path.join(video_output_dir, f"{video_name}_annotated_fixed.mp4")
    db_path = os.path.join(video_output_dir, f"{video_name}_events.db")
    event_log_csv = os.path.join(video_output_dir, f"{video_name}_event_log.csv")

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("Could not open:", video_path)
        continue

    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps <= 0:
        fps = 25

    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    min_loiter_frames = int(MIN_LOITER_SECONDS * fps)
    min_vehicle_gather_frames = int(MIN_VEHICLE_GATHER_SECONDS * fps)
    max_missing_frames = int(MAX_MISSING_SECONDS * fps)

    writer = cv2.VideoWriter(
        raw_output_video,
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (frame_width, frame_height)
    )

    # -------------------------
    # DATABASE TABLES
    # -------------------------
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute("DROP TABLE IF EXISTS current_suspicious_events")
    cursor.execute("DROP TABLE IF EXISTS suspicious_event_history")

    cursor.execute("""
    CREATE TABLE current_suspicious_events (
        event_id INTEGER PRIMARY KEY AUTOINCREMENT,
        video_name TEXT,
        event_type TEXT,
        person_id TEXT,
        object_track_id INTEGER,
        event_start_time TEXT,
        last_seen_time TEXT,
        duration_seconds REAL,
        status TEXT,
        summary TEXT
    )
    """)

    cursor.execute("""
    CREATE TABLE suspicious_event_history (
        history_id INTEGER PRIMARY KEY AUTOINCREMENT,
        video_name TEXT,
        event_type TEXT,
        person_id TEXT,
        object_track_id INTEGER,
        event_start_time TEXT,
        event_end_time TEXT,
        duration_seconds REAL,
        final_status TEXT,
        action_taken TEXT,
        summary TEXT
    )
    """)

    conn.commit()

    tracks = {}
    next_track_id = 1
    active_event_ids = {}
    vehicle_gather_counter = 0
    event_log_rows = []
    frame_idx = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        results = model.predict(source=frame, conf=CONF_THRESHOLD, verbose=False)
        annotated_frame = frame.copy()

        current_person_detections = []
        current_vehicle_centers = []

        # -------------------------
        # DETECTION
        # -------------------------
        for r in results:
            if r.boxes is None or len(r.boxes) == 0:
                continue

            for box in r.boxes:
                cls_id = int(box.cls[0])
                label_name = model.names[cls_id]

                if is_person_label(label_name):
                    class_name = "person"
                elif is_vehicle_label(label_name):
                    class_name = "vehicle"
                else:
                    continue

                confidence = float(box.conf[0])
                x1, y1, x2, y2 = box.xyxy[0].tolist()
                cx = int((x1 + x2) / 2)
                cy = int((y1 + y2) / 2)

                color = (0, 255, 0) if class_name == "person" else (255, 0, 0)

                cv2.rectangle(
                    annotated_frame,
                    (int(x1), int(y1)),
                    (int(x2), int(y2)),
                    color,
                    2
                )

                cv2.putText(
                    annotated_frame,
                    f"{class_name} {confidence:.2f}",
                    (int(x1), int(y1) - 8),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.5,
                    color,
                    2
                )

                if class_name == "person":
                    current_person_detections.append({
                        "center_x": cx,
                        "center_y": cy,
                        "box": (x1, y1, x2, y2)
                    })

                if class_name == "vehicle":
                    current_vehicle_centers.append((cx, cy))

        current_vehicle_count = len(current_vehicle_centers)

        # -------------------------
        # PERSON TRACKING
        # -------------------------
        matched_track_ids = set()

        for det in current_person_detections:
            cx = det["center_x"]
            cy = det["center_y"]

            best_track_id = None
            best_distance = float("inf")

            for track_id, data in tracks.items():
                last_x, last_y = data["positions"][-1]
                dist = math.sqrt((cx - last_x) ** 2 + (cy - last_y) ** 2)

                if dist < DIST_THRESHOLD and dist < best_distance and track_id not in matched_track_ids:
                    best_track_id = track_id
                    best_distance = dist

            if best_track_id is not None:
                tracks[best_track_id]["positions"].append((cx, cy))
                tracks[best_track_id]["last_seen_frame"] = frame_idx
                matched_track_ids.add(best_track_id)
                det["track_id"] = best_track_id
            else:
                tracks[next_track_id] = {
                    "positions": [(cx, cy)],
                    "last_seen_frame": frame_idx,
                    "loitering": False,
                    "near_vehicle_counter": 0
                }
                det["track_id"] = next_track_id
                matched_track_ids.add(next_track_id)
                next_track_id += 1

        # -------------------------
        # VEHICLE PROXIMITY CHECK
        # -------------------------
        for det in current_person_detections:
            track_id = det["track_id"]
            px, py = det["center_x"], det["center_y"]

            if track_id not in tracks:
                continue

            min_vehicle_dist = min_distance_to_any_vehicle((px, py), current_vehicle_centers)

            if min_vehicle_dist < VEHICLE_PROXIMITY_THRESHOLD:
                tracks[track_id]["near_vehicle_counter"] += 1
            else:
                tracks[track_id]["near_vehicle_counter"] = 0

        # -------------------------
        # LOITERING DETECTION
        # -------------------------
        for track_id, data in list(tracks.items()):
            positions = data["positions"]

            if len(positions) >= min_loiter_frames:
                start_x, start_y = positions[0]
                end_x, end_y = positions[-1]

                total_distance = math.sqrt(
                    (end_x - start_x) ** 2 + (end_y - start_y) ** 2
                )

                vehicle_interaction_like = (
                    data["near_vehicle_counter"] > 0 and
                    data["near_vehicle_counter"] < min_loiter_frames // 2
                )

                if total_distance < LOITER_DISTANCE_THRESHOLD and not vehicle_interaction_like:
                    tracks[track_id]["loitering"] = True
                    event_key = ("loitering", track_id)

                    if event_key not in active_event_ids:
                        event_start_time = frame_to_timestamp(frame_idx, fps)
                        person_id = person_label(track_id)

                        summary = (
                            f"{person_id} remained in nearly the same location for more than "
                            f"{MIN_LOITER_SECONDS} seconds. Loitering was detected at video time "
                            f"{event_start_time}."
                        )

                        cursor.execute("""
                            INSERT INTO current_suspicious_events
                            (video_name, event_type, person_id, object_track_id, event_start_time,
                             last_seen_time, duration_seconds, status, summary)
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """, (
                            video_name,
                            "Loitering",
                            person_id,
                            track_id,
                            event_start_time,
                            event_start_time,
                            0,
                            "Active",
                            summary
                        ))
                        conn.commit()

                        event_id = cursor.lastrowid
                        active_event_ids[event_key] = event_id

                        event_log_rows.append({
                            "video_time": event_start_time,
                            "action": "INSERT",
                            "event_id": event_id,
                            "event_type": "Loitering",
                            "person_id": person_id,
                            "summary": summary
                        })

                    else:
                        event_id = active_event_ids[event_key]
                        last_seen_time = frame_to_timestamp(frame_idx, fps)

                        current_duration = duration_seconds(
                            max(0, frame_idx - min_loiter_frames),
                            frame_idx,
                            fps
                        )

                        cursor.execute("""
                            UPDATE current_suspicious_events
                            SET last_seen_time = ?, duration_seconds = ?
                            WHERE event_id = ?
                        """, (last_seen_time, current_duration, event_id))
                        conn.commit()

                else:
                    tracks[track_id]["loitering"] = False
                    event_key = ("loitering", track_id)

                    if event_key in active_event_ids:
                        event_id = active_event_ids[event_key]
                        event_end_time = frame_to_timestamp(frame_idx, fps)

                        cursor.execute("""
                            SELECT video_name, event_type, person_id, object_track_id,
                                   event_start_time, last_seen_time, duration_seconds, summary
                            FROM current_suspicious_events
                            WHERE event_id = ?
                        """, (event_id,))
                        row = cursor.fetchone()

                        if row is not None:
                            action_taken = (
                                "Removed from active suspicious table because the person moved away "
                                "or no longer satisfied the loitering condition."
                            )

                            final_summary = (
                                f"{row[2]} was detected as loitering from {row[4]} to {event_end_time}. "
                                f"The person stayed for approximately {row[6]} seconds after the event "
                                f"was confirmed. The event was moved to history because the person moved away."
                            )

                            cursor.execute("""
                                INSERT INTO suspicious_event_history
                                (video_name, event_type, person_id, object_track_id, event_start_time,
                                 event_end_time, duration_seconds, final_status, action_taken, summary)
                                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                            """, (
                                row[0],
                                row[1],
                                row[2],
                                row[3],
                                row[4],
                                event_end_time,
                                row[6],
                                "Resolved",
                                action_taken,
                                final_summary
                            ))

                        cursor.execute(
                            "DELETE FROM current_suspicious_events WHERE event_id = ?",
                            (event_id,)
                        )
                        conn.commit()
                        del active_event_ids[event_key]

                        event_log_rows.append({
                            "video_time": event_end_time,
                            "action": "DELETE",
                            "event_id": event_id,
                            "event_type": "Loitering",
                            "person_id": person_label(track_id),
                            "summary": "Removed because the person moved away or loitering condition ended."
                        })

        # -------------------------
        # REMOVE TRACKS MISSING TOO LONG
        # -------------------------
        tracks_to_remove = []

        for track_id, data in tracks.items():
            missing_count = frame_idx - data["last_seen_frame"]

            if missing_count > max_missing_frames:
                tracks_to_remove.append(track_id)

        for track_id in tracks_to_remove:
            event_key = ("loitering", track_id)

            if event_key in active_event_ids:
                event_id = active_event_ids[event_key]
                event_end_time = frame_to_timestamp(frame_idx, fps)

                cursor.execute("""
                    SELECT video_name, event_type, person_id, object_track_id,
                           event_start_time, last_seen_time, duration_seconds, summary
                    FROM current_suspicious_events
                    WHERE event_id = ?
                """, (event_id,))
                row = cursor.fetchone()

                if row is not None:
                    action_taken = (
                        f"Removed from active suspicious table because the person was not detected "
                        f"for more than {MAX_MISSING_SECONDS} seconds."
                    )

                    final_summary = (
                        f"{row[2]} was detected as loitering from {row[4]} to {event_end_time}. "
                        f"The person stayed for approximately {row[6]} seconds after confirmation. "
                        f"The event was moved to history because the person disappeared from the video."
                    )

                    cursor.execute("""
                        INSERT INTO suspicious_event_history
                        (video_name, event_type, person_id, object_track_id, event_start_time,
                         event_end_time, duration_seconds, final_status, action_taken, summary)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, (
                        row[0],
                        row[1],
                        row[2],
                        row[3],
                        row[4],
                        event_end_time,
                        row[6],
                        "Resolved",
                        action_taken,
                        final_summary
                    ))

                cursor.execute(
                    "DELETE FROM current_suspicious_events WHERE event_id = ?",
                    (event_id,)
                )
                conn.commit()
                del active_event_ids[event_key]

                event_log_rows.append({
                    "video_time": event_end_time,
                    "action": "DELETE",
                    "event_id": event_id,
                    "event_type": "Loitering",
                    "person_id": person_label(track_id),
                    "summary": f"Removed because the person was missing for more than {MAX_MISSING_SECONDS} seconds."
                })

            del tracks[track_id]

        # -------------------------
        # VEHICLE GATHERING DETECTION
        # -------------------------
        if current_vehicle_count >= VEHICLE_COUNT_THRESHOLD:
            vehicle_gather_counter += 1
        else:
            vehicle_gather_counter = 0

        vehicle_event_key = ("vehicle_gathering", 0)

        if vehicle_gather_counter >= min_vehicle_gather_frames:
            if vehicle_event_key not in active_event_ids:
                event_start_time = frame_to_timestamp(frame_idx, fps)

                summary = (
                    f"Vehicle gathering was detected at video time {event_start_time}. "
                    f"At least {VEHICLE_COUNT_THRESHOLD} vehicles remained visible for more than "
                    f"{MIN_VEHICLE_GATHER_SECONDS} seconds."
                )

                cursor.execute("""
                    INSERT INTO current_suspicious_events
                    (video_name, event_type, person_id, object_track_id, event_start_time,
                     last_seen_time, duration_seconds, status, summary)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    video_name,
                    "Vehicle Gathering",
                    "Vehicle Group",
                    None,
                    event_start_time,
                    event_start_time,
                    0,
                    "Active",
                    summary
                ))
                conn.commit()

                event_id = cursor.lastrowid
                active_event_ids[vehicle_event_key] = event_id

                event_log_rows.append({
                    "video_time": event_start_time,
                    "action": "INSERT",
                    "event_id": event_id,
                    "event_type": "Vehicle Gathering",
                    "person_id": "Vehicle Group",
                    "summary": summary
                })

            else:
                event_id = active_event_ids[vehicle_event_key]
                last_seen_time = frame_to_timestamp(frame_idx, fps)

                current_duration = duration_seconds(
                    max(0, frame_idx - min_vehicle_gather_frames),
                    frame_idx,
                    fps
                )

                cursor.execute("""
                    UPDATE current_suspicious_events
                    SET last_seen_time = ?, duration_seconds = ?
                    WHERE event_id = ?
                """, (last_seen_time, current_duration, event_id))
                conn.commit()

        else:
            if vehicle_event_key in active_event_ids:
                event_id = active_event_ids[vehicle_event_key]
                event_end_time = frame_to_timestamp(frame_idx, fps)

                cursor.execute("""
                    SELECT video_name, event_type, person_id, object_track_id,
                           event_start_time, last_seen_time, duration_seconds, summary
                    FROM current_suspicious_events
                    WHERE event_id = ?
                """, (event_id,))
                row = cursor.fetchone()

                if row is not None:
                    action_taken = (
                        "Moved to history because the number of visible vehicles dropped below "
                        f"{VEHICLE_COUNT_THRESHOLD}."
                    )

                    final_summary = (
                        f"Vehicle gathering was detected from {row[4]} to {event_end_time}. "
                        f"The event lasted approximately {row[6]} seconds after confirmation."
                    )

                    cursor.execute("""
                        INSERT INTO suspicious_event_history
                        (video_name, event_type, person_id, object_track_id, event_start_time,
                         event_end_time, duration_seconds, final_status, action_taken, summary)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, (
                        row[0],
                        row[1],
                        row[2],
                        row[3],
                        row[4],
                        event_end_time,
                        row[6],
                        "Resolved",
                        action_taken,
                        final_summary
                    ))

                cursor.execute(
                    "DELETE FROM current_suspicious_events WHERE event_id = ?",
                    (event_id,)
                )
                conn.commit()
                del active_event_ids[vehicle_event_key]

                event_log_rows.append({
                    "video_time": event_end_time,
                    "action": "DELETE",
                    "event_id": event_id,
                    "event_type": "Vehicle Gathering",
                    "person_id": "Vehicle Group",
                    "summary": "Removed because visible vehicle count dropped below threshold."
                })

        # -------------------------
        # DRAW OUTPUT LABELS
        # -------------------------
        for det in current_person_detections:
            track_id = det["track_id"]
            x1, y1, x2, y2 = det["box"]

            cv2.putText(
                annotated_frame,
                f"{person_label(track_id)}",
                (int(x1), int(y2) + 15),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                (0, 255, 255),
                2
            )

            loiter_key = ("loitering", track_id)

            if loiter_key in active_event_ids:
                cv2.putText(
                    annotated_frame,
                    f"ALERT: LOITERING {person_label(track_id)}",
                    (int(x1), int(y1) - 25),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6,
                    (0, 0, 255),
                    2
                )

        cv2.putText(
            annotated_frame,
            f"Vehicles: {current_vehicle_count}",
            (20, 35),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (255, 255, 255),
            2
        )

        if vehicle_event_key in active_event_ids:
            cv2.putText(
                annotated_frame,
                "ALERT: VEHICLE GATHERING",
                (20, 70),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.8,
                (0, 0, 255),
                2
            )

        writer.write(annotated_frame)
        frame_idx += 1

    # -------------------------
    # CLOSE ACTIVE EVENTS AT VIDEO END
    # -------------------------
    for event_key, event_id in list(active_event_ids.items()):
        event_end_time = frame_to_timestamp(frame_idx, fps)

        cursor.execute("""
            SELECT video_name, event_type, person_id, object_track_id,
                   event_start_time, last_seen_time, duration_seconds, summary
            FROM current_suspicious_events
            WHERE event_id = ?
        """, (event_id,))
        row = cursor.fetchone()

        if row is not None:
            action_taken = "Video ended while this suspicious event was still active."

            final_summary = (
                f"{row[2]} had an active {row[1]} event from {row[4]} until the video ended at "
                f"{event_end_time}. The event remained active at the end of the video."
            )

            cursor.execute("""
                INSERT INTO suspicious_event_history
                (video_name, event_type, person_id, object_track_id, event_start_time,
                 event_end_time, duration_seconds, final_status, action_taken, summary)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                row[0],
                row[1],
                row[2],
                row[3],
                row[4],
                event_end_time,
                row[6],
                "Active at video end",
                action_taken,
                final_summary
            ))

    conn.commit()

    # -------------------------
    # FINALISE VIDEO
    # -------------------------
    cap.release()
    writer.release()

    event_log_df = pd.DataFrame(event_log_rows)
    event_log_df.to_csv(event_log_csv, index=False)

    current_df = pd.read_sql_query("SELECT * FROM current_suspicious_events", conn)
    history_df = pd.read_sql_query("SELECT * FROM suspicious_event_history", conn)

    conn.close()

    !ffmpeg -y -i "{raw_output_video}" -vcodec libx264 -pix_fmt yuv420p -movflags +faststart "{fixed_output_video}" -loglevel error

    final_video_paths.append(fixed_output_video)

    print("\nACTIVE suspicious events for", video_name)
    show_full_table(current_df)

    print("\nEvent history for", video_name)
    show_full_table(history_df)

    print("\nEvent log preview for", video_name)
    show_full_table(event_log_df.head(20))

    print("Annotated output video:", fixed_output_video)
    print("SQLite database:", db_path)
    print("Event log CSV:", event_log_csv)

# -------------------------
# 7. DISPLAY ALL OUTPUT VIDEOS
# -------------------------
print("\n==============================")
print("ALL OUTPUT VIDEOS")
print("==============================")

for vp in final_video_paths:
    print(vp)
    display(play_video_html(vp))